name: PR Pylint, PEP8 and Pytest

on: pull_request

jobs:
  test_pylint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Get changed Python files
      uses: dorny/paths-filter@v2
      id: paths-filter
      with:
        list-files: 'shell'
        filters: |
          code:
            - added|modified: '!(ranger/config)**.py'
          config:
            - added|modified: 'ranger/config/**.py'
    - name: Lint code with Flake8 and Pylint
      if: ${{ steps.path-filter.outputs.code == 'true' }}
      run: |
        flake8 ${{ steps.paths-filter.outputs.code_files }}
        pylint ${{ steps.paths-filter.outputs.code_files }}
    - name: Lint config with Flake8 and Pylint
      if: ${{ steps.path-filter.outputs.config == 'true' }}
      run: |
        flake8 ${{ steps.paths-filter.outputs.config }}
        pylint --rcfile=ranger/config/.pylintrc \
          ${{ steps.paths-filter.outputs.config_files }}
    - name: Test code with Pytest
      if: ${{ steps.path-filter.outputs.code == 'true' }}
      run: |
        make test_pytest
